### ISSUE TITLE
Add in Pagination and limit to X rows

### ISSUE THREAD

**Issue by no1youknowz** [davidguttman/react-pivot#1]
Hey,

I thought this was amazing.  But if you can add in 10,25,50,100 rows and then be able to paginate.  Would be awesome!

Thanks

**Comment by davidguttman** [comment]
I've been thinking about pagination, and it's not very straightforward feature.

A simple approach could be to paginate the number of rows in the HTML table, but if the boundary occurs in the middle of a sub-dimension, the following "page" will be missing the parent rows that provide context.

Another approach would just be to set the number of top-level rows, but that's not very useful as just 4 top-level rows could have thousands of children.

The answer might be to do the "simple" approach, but start the table with all the parents of the first row of the new "page"

**Comment by davidguttman** [comment]
Added in `v1.4.0`
