### ISSUE TITLE
Sort sometimes works strangely with 2nd dimension

### ISSUE THREAD

**Issue by tristanreid** [davidguttman/react-pivot#2]
Awesome tool!!!  Looks beautiful.

Using the example on https://davidguttman.github.io/react-pivot/

I set the dimensions to first and last name.  Tried sorting on the last name, it seems to have a rational behavior, but if you the click the sort on last name again to reverse direction, it doesn't make any sense.

I think sorting on a sub-dimension should probably leave higher dimensions fixed, or something like it should use only the first entry of the current dimension to determine the order of higher dimensions.

**Comment by davidguttman** [comment]
Thanks for the issue!

I just changed it so that if a sub-dimension doesn't have a sort value, it will use the dimension values it _does_ have instead. Let me know what you think: https://davidguttman.github.io/react-pivot/

**Comment by tristanreid** [comment]
Very nice!  Thanks!
