### ISSUE TITLE
how to drill down an array?

### ISSUE THREAD

**Issue by luisrudge** [davidguttman/react-pivot#22]
Imagine that you have a list of transations instead of just one transaction (following your example). How would you drill down those transactions?

**Comment by davidguttman** [comment]
Sorry for the delay on this!

Assuming I understand the question, the best thing to do would be to run a transform to get the formatted the way you want:

```js
var rawData = [
  {name: 'David', transactions: [
    id: 1, amount: 100,
    id: 2, amount: 200
  ]}
]

var dataForPivot = []
rawData.forEach(function (rawItem) {
  rawItem.transactions.forEach(function (t) {
    dataForPivot.push({
      name: rawItem.name,
      id: t.id,
      amount: t.amount
    })
  })
})

// now use dataForPivot
```

**Comment by luisrudge** [comment]
Yeah, I did exactly that back then.. Thanks!
