### ISSUE TITLE
Module parse failed with webpack

### ISSUE THREAD

**Issue by nicolas-despres** [davidguttman/react-pivot#23]
Hi,
It is probably related to my yet limited knowlegde of weback but I installed this repo using npm and added 
```javascript
import ReactPivot from 'react-pivot';
```
As I am using ES6 in my project.
When I run my build I have the following error occuring:

```javascript
ERROR in ./~/react-pivot/index.jsx
Module parse failed: C:\myfrontend\node_modules\react-pivot\index.jsx Line 197:
Unexpected token <
You may need an appropriate loader to handle this file type.
```
I did the same process with other libraries and did not have such error message.
Thanks in advance

**Comment by davidguttman** [comment]
I'm not familiar with webpack either, but I'm guessing that it's having trouble with the html tags in the jsx file. I'd recommend looking into how to set up https://babeljs.io/ with webpack or just use http://browserify.org/ which should just work.

**Comment by nicolas-despres** [comment]
Yes you are right - let me close this as this has probably nothing to do with your library, sorry about that
Nicolas

**Comment by calebdel** [comment]
@nicolas-despres can you share how you have webpack setup with babel to get react-pivot working? I'm getting the same error you were.

**Comment by r1g0** [comment]
I'm having this same problem, has anyone found a way to make it work?

**Comment by nicolas-despres** [comment]
Sorry I have not yet

**Comment by ayozebarrera** [comment]
I'm having the same problem and I have a lot components working with jsx but the only one failing is index.jsx from your package. Anyone know how solve it?

**Comment by Kamps-Duac** [comment]
see my answer on #47
