### ISSUE TITLE
Module parse failed with webpack

### ISSUE THREAD

**Issue by ayozebarrera** [davidguttman/react-pivot#31]
Same as #23 

I installed your package and has the following error ```You may need an appropriate loader to handle this file type.``` in react-pivot/index.jsx

I have others components with jsx working well time ago... any solution?

**Comment by ayozebarrera** [comment]
I had to add the following loaders to my webpack.config.js

```
{
  test: /\.(js|jsx|es6)$/,
  include: /react-pivot/,
  loader: 'babel'
}
```
and will solve this problem. After that I had the same error but in a .css file used by index.jsx so had to add the following, in loaders too:

```
{ 
  test: /\.css$/,
  loader: "style-loader!css-loader"
}
```

After this, I can render the component but with the following warning #32

**Comment by davidguttman** [comment]
Unfortunately, I don't use `webpack`, so I don't really know why that's needed.

Happy to take a PR if there's anything simple to make `react-pivot` work better with it.

**Comment by PrudhviRaj5** [comment]
@ayozebarrera Did you figure this out? The same error occurs to me and I'm using babel, webpack server and using ES6 in my complete project. I tried what you suggested in modifying webpack.config.js, but still no luck :(

**Comment by PrudhviRaj5** [comment]
I added this line to my webpack.config.js `{test: /\.(js|jsx|es6)$/, include: /react-pivot/, loader: "babel", query: {presets: ["es2015", "react"]}},`
and voila! it started working :+1:

**Comment by ayozebarrera** [comment]
Great @PrudhviRaj5. I had that query aswell but not on the same place

**Comment by ayozebarrera** [comment]
Clossing Issue.
