### ISSUE TITLE
Warning: bind()

### ISSUE THREAD

**Issue by ayozebarrera** [davidguttman/react-pivot#32]
After spending hours solving #31 I get the following message after rendering your component

```
Warning: bind(): You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call. See exports
```
in the dimensions.jsx render.

Too much headache use your package with my config... and I see low activity in this project so I'm not sure about use it. 

Ignoring the warning, the component seems to work well...

Wish you luck with this, hope you update it soon ^^

**Comment by davidguttman** [comment]
Sorry about that, fixed!

**Comment by ayozebarrera** [comment]
Whoa, great

Thanks for the speed :D
