### ISSUE TITLE
reduced bundle size

### ISSUE THREAD

**Issue by cdaringe** [davidguttman/react-pivot#35]
hello!

i see a some `requires` where `lodash` is required in as full.  [ref](https://github.com/davidguttman/react-pivot/blob/master/lib/column-control.jsx#L1)

if instead a `require('lodash/someFun')` is used, the bundler of choice (webpack/browserify) won't need to included the full library.

easy kbs worth saving!

thanks for the lib

**Comment by davidguttman** [comment]
Good call, will need to do that in the `dataframe` dependency too, otherwise it could actually increase the size.
