### ISSUE TITLE
make dimension filter display optional

### ISSUE THREAD

**Issue by mrsmuneton** [davidguttman/react-pivot#38]
Would be nice if there was a way to configure if the user filters to be hidden, and make this bit here never return the markup:
https://github.com/davidguttman/react-pivot/blob/master/lib/dimensions.jsx#L19

**Comment by davidguttman** [comment]
What about here instead? https://github.com/davidguttman/react-pivot/blob/master/index.jsx#L101

**Comment by Kamps-Duac** [comment]
Added documentation for this property flag in PR #48
