### ISSUE TITLE
Example of setting solo option

### ISSUE THREAD

**Issue by tanyona** [davidguttman/react-pivot#49]
Trying to figure out the solo option.

Given a standalone implementation (no react) and the following configuration

	var rows = [
		{
			"firstName": "Francisco",
			"lastName": "Brekke"	
		},
		{
			"firstName": "Anne",
			"lastName": "Doe"	
		}
	];

	var solo={
		"firstName": "Francisco",
		"lastName": "Brekke"	
	};

	ReactPivot(document.getElementById('reactPivotOutput'), {
		rows: rows,
		dimensions: dimensions,
		calculations: calculations,
		reduce: reduce,		
		solo: solo
	});

What should the setting for solo be to activate a record as solo. (I've omitted the dimensions, etc from the example. I'm thinking they are not related to the solo setting)

**Comment by davidguttman** [comment]
It would look like this: `{"title":"First Name","value":"Francisco"}`

Note that `title` is the `title` set in `dimensions`, and that you can only have one solo at a time.

**Comment by tanyona** [comment]
Noted. Thanks. Just tried it out and it works. I'd looked around but hadn't seen anything in the documentation or examples explaining this.
