### ISSUE TITLE
Too big in size

### ISSUE THREAD

**Issue by FractalizeR** [davidguttman/react-pivot#5]
That's a nice piece of work, but... 200Kb minified just for library code? Can't it be broken into small modules, that can be used independently, for instance? May be, most of the users will not require ALL the features.

**Comment by davidguttman** [comment]
Of course! The 200kb is the "standalone" version which includes `React`. If you're using [browserify](https://github.com/substack/node-browserify), `ReactPivot` will only add modules that are missing and will be much, much, much smaller. If you're already using `React` this module will only add about 20k, and if you're also already using `lodash` it will be only 4kb. 

The "standalone" version is just a convenience for people who aren't using something like `browserify` and don't care about the extra size.

If you aren't using `React` and don't want those features, feel free to just use [DataFrame](https://github.com/davidguttman/node-dataframe) as it does a lot of the work.

**Comment by FractalizeR** [comment]
I see now, thanks ;)
