### ISSUE TITLE
Effect of defaultStyles option

### ISSUE THREAD

**Issue by tanyona** [davidguttman/react-pivot#50]
I'm using the standalone react-pivot. Tried setting defaultStyles as true or false but not seeing any difference. What is the expected effect and is there anything extra I need to do to see the difference. A snippet of my configuration is as below.

	<script type="text/javascript" src="${pageContext.request.contextPath}/js/react-pivot-1.18.3/react-pivot-standalone-1.18.2.min.js"></script>
	
	var defaultStyles=false; //true, false no difference? looks good either way
	
	ReactPivot(document.getElementById('reactPivotOutput'), {
		rows: rows,
		dimensions: dimensions,
		calculations: calculations,
		reduce: reduce,		
		defaultStyles: defaultStyles
	});

Do I need to put the style.css file in a certain location to see the difference. I'm currently not including it.

**Comment by davidguttman** [comment]
You can change the settings and see the difference here: http://codepen.io/anon/pen/ygjLvm?editors=1010

Here's `defaultStyles: false`:
![image](https://cloud.githubusercontent.com/assets/431696/22566297/28d7f1ec-e940-11e6-9490-ecec991b4531.png)

Here's `defaultStyle: true`:
![image](https://cloud.githubusercontent.com/assets/431696/22566321/475a17d0-e940-11e6-9bbd-5fcb61d5a89c.png)

**Comment by tanyona** [comment]
Sure. Works as advertised. Perhaps a caching issue on my end.
