### ISSUE TITLE
this.rows.forEach is not a function

### ISSUE THREAD

**Issue by muxica** [davidguttman/react-pivot#52]
Followed your example as well as the react 14/15 fixes in #47 and when run, getting this error:

Uncaught TypeError: this.rows.forEach is not a function. 

The error is coming from the dataframe dependency. Which is another of your repos. I'm opening this here however since my first thought is that something isn't being passed correctly to dataframe from ReactPivot.

**Comment by davidguttman** [comment]
This most likely means that ReactPivot / dataframe was not passed an array as `rows`. Is there a repo I can look at?

**Comment by muxica** [comment]
I actually just figured it out after posting. I had a misspelling in my json datasource file name. Gonna switch it from fake data later but that's what was wrong. Going to close now. Thanks for the rapid response!
