### ISSUE TITLE
Custom styles

### ISSUE THREAD

**Issue by shubhang93** [davidguttman/react-pivot#53]
I am unable to style the background color of the Pivot table, I want to remove the box shadow and change the background color. After passing defaultStyles = {false} what other props should I pass so that I can change the styles. It still uses Styles.css in the React Pivot node_modules folder.

**Comment by davidguttman** [comment]
Not sure what's causing the issue. Whether or not RP loads styles is a simple conditional: https://github.com/davidguttman/react-pivot/blob/master/index.jsx#L61

**Comment by shubhang93** [comment]
Solved the issue, it my fault. I wasn't importing my custom CSS file on the page where I was using React Pivot. Another question , can I add on click events to selected rows .

**Comment by davidguttman** [comment]
Not at the moment, but that sounds like a useful feature if you want to submit a PR.
