### ISSUE TITLE
Question about "Export CSV"

### ISSUE THREAD

**Issue by ryexley** [davidguttman/react-pivot#6]
I have a question about the "Export CSV" button. In the demo, that button doesn't appear to actually do anything...and I can't seem to determine from anywhere in any documentation or examples if that is an actual, functional button out-of-the-box, or if it's just part of the example. Does clicking that button actually generate a .csv file for download by users, or is that just a UI hook for executing a function to call out to a server function for generating/downloading a CSV of the data represented by the grid?

Thanks for the help.

**Comment by davidguttman** [comment]
Totally a bug, thanks for opening the issue! 

Just found where I broke it, and hope to have it fixed soon.
