### ISSUE TITLE
characters of chinese appear as gibberish  In  MS Excel

### ISSUE THREAD

**Issue by ghyghoo8** [davidguttman/react-pivot#61]
table.csv opened by MS Excel , all characters of chinese appear as  gibberish .

I fixed it at 4 line in lib/download.js 

> var blob = new Blob(["\ufeff"+content], { type: mime })

please merge it.

**Comment by davidguttman** [comment]
Sorry for the delay, thanks for reporting this issue.

When I try that fix, I see a weird character:

![image](https://user-images.githubusercontent.com/431696/34966474-ce22636c-fa10-11e7-87c9-ceb9afc32e65.png)

Is there something else we can try?
