### ISSUE TITLE
How we can use dimenstions for array of objects inside.

### ISSUE THREAD

**Issue by gmmurugan** [davidguttman/react-pivot#63]
eg:
[
  {
    "firstName": "Francisco",
    "lastName": "Brekke",
    "state": "NY",
    "transactions": [{
      "amount": "399.73",
      "date": "2012-02-02T08:00:00.000Z",
      "business": "Kozey-Moore",
      "name": "Checking Account 2297",
      "type": "deposit",
      "account": "82741327"
    },
   {
      "amount": "399.73",
      "date": "2012-02-02T08:00:00.000Z",
      "business": "Kozey-Moore",
      "name": "Checking Account 2297",
      "type": "withdrawal",
      "account": "82741327"
    }
]
}
]

and i want the dimensions to get type of transactions..

**Comment by davidguttman** [comment]
Sorry for the delay on this.

If the most granular level you're interested in (e.g. what you want to see when *all* dimensions are visible) are individual transactions, you'd want to transform the data before giving it to RP. Something like:

```js
var transactions = []
people.forEach(function (person) {
  person.transactions.forEach(function (tx) {
    tx.firstName = person.firstName
    tx.lastName = person.lastName
    tx.state = person.state
    transactions.push(tx)
  })
})
```

Then you could just have a dimension `type`.
